Adding note when missing config

diff --git a/bin/hubot b/bin/hubot
--- a/bin/hubot
+++ b/bin/hubot
@@ -1,8 +1,13 @@
 #!/bin/sh
 
 set -e
+if [ -f .env ]; then
+  . .env
+  npm install
+  export PATH="node_modules/.bin:node_modules/hubot/node_modules/.bin:$PATH"
 
-npm install
-export PATH="node_modules/.bin:node_modules/hubot/node_modules/.bin:$PATH"
-
-exec node_modules/.bin/hubot --name "cowbot" "$@"
+  exec node_modules/.bin/hubot --name "cowbot" "$@"
+else
+  echo "Cannot find .env config file.  Please view .env.sample for an example."
+  exit 1
+fi
